version: 2
updates:
  - package-ecosystem: 'npm'
    # Files stored in `app` directory
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    ignore:
      - dependency-name: 'commander'
